version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/letsencrypt:/letsencrypt
    command: --configFile=/traefik.yml
    networks:
      - main-network
  app:
    build: .
    env_file:
      - .envs/.django  # Django ortam değişkenleri
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - static-data:/app/static
    networks:
      - main-network
    labels:  # TRAEFİK İÇİN KRİTİK!
      - "traefik.enable=true"
      - "traefik.http.routers.django-https.rule=Host(`superisi.net`) || Host(`www.superisi.net`)"
      - "traefik.http.routers.django-https.entrypoints=websecure"
      - "traefik.http.routers.django-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.django.loadbalancer.server.port=8000"  # Django portu
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .envs/.db
    networks:
      - main-network

# Ağ ve Volume tanımları
networks:
  main-network:
    driver: bridge

volumes:
  postgres-data:
  static-data: