version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik.yml:ro
      - ./acme.json:/acme.json
    networks:
      - web

  app:
    build:
      context: .
    container_name: recipe-app
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static-data:/vol/web
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipeapi.rule=Host(`superisi.net`)"
      - "traefik.http.routers.recipeapi.entrypoints=websecure"
      - "traefik.http.routers.recipeapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.recipeapi.loadbalancer.server.port=8000"
    networks:
      - web

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - web
volumes:
  postgres-data:
  static-data:

networks:
  web:
    external: false