entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: sami.devrim@gmail.com  # LET'S ENCRYPT İÇİN GERÇEK MAIL
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
http:
  routers:
    www-redirect:
      rule: "Host(`www.superisi.net`)"
      entryPoints:
        - "websecure"
      middlewares:
        - redirect-nonwww
      service: dummy # Gerçek servis yerine geçici

  middlewares:
    redirect-nonwww:
      redirectRegex:
        regex: "^(https?://)www\\.(.+)"
        replacement: "${1}${2}"
        permanent: true